import React from 'react';
import Head from 'next/head'

const Header = () => {
  return (
    <Head>
        <title>HMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ui-logo.svg" />
    </Head>
  );
};

export default Header;